services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "31883:31883"
      - "9001:9001"
    depends_on:
      - db

  python-service:
    build: ./python-service
    volumes:
      - ./db:/db
    depends_on:
      - mosquitto
      - db

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./db:/db
      # - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    depends_on:
      - python-service
      - db

  db:
    build: ./db
    volumes:
      - ./db:/db

volumes:
  grafana-data: